HOTELS = [
    {
        "property_id": 1001,
        "name": "Hilton Garden Inn London",
        "city": "London",
        "country": "United Kingdom",
        "stars": 4,
    },
    {
        "property_id": 1002,
        "name": "Marriott Downtown Dubai",
        "city": "Dubai",
        "country": "United Arab Emirates",
        "stars": 5,
    },
    {
        "property_id": 1003,
        "name": "Hyatt Regency Tokyo",
        "city": "Tokyo",
        "country": "Japan",
        "stars": 5,
    },
    {
        "property_id": 1004,
        "name": "Sheraton Bangkok",
        "city": "Bangkok",
        "country": "Thailand",
        "stars": 5,
    },
    {
        "property_id": 1005,
        "name": "Novotel Paris Centre",
        "city": "Paris",
        "country": "France",
        "stars": 4,
    },
    {
        "property_id": 1006,
        "name": "Pullman Singapore Orchard",
        "city": "Singapore",
        "country": "Singapore",
        "stars": 5,
    },
    {
        "property_id": 1007,
        "name": "Westin New York Times Square",
        "city": "New York",
        "country": "United States",
        "stars": 5,
    },
    {
        "property_id": 1008,
        "name": "Holiday Inn Sydney Harbour",
        "city": "Sydney",
        "country": "Australia",
        "stars": 4,
    },
    {
        "property_id": 1009,
        "name": "Radisson Blu Berlin",
        "city": "Berlin",
        "country": "Germany",
        "stars": 4,
    },
    {
        "property_id": 1010,
        "name": "Fairmont Vancouver",
        "city": "Vancouver",
        "country": "Canada",
        "stars": 5,
    },
    {
        "property_id": 1011,
        "name": "Mercure Rome Centro",
        "city": "Rome",
        "country": "Italy",
        "stars": 4,
    },
    {
        "property_id": 1012,
        "name": "Crowne Plaza Madrid",
        "city": "Madrid",
        "country": "Spain",
        "stars": 4,
    },
    {
        "property_id": 1013,
        "name": "DoubleTree Amsterdam",
        "city": "Amsterdam",
        "country": "Netherlands",
        "stars": 4,
    },
    {
        "property_id": 1014,
        "name": "Le Méridien Kuala Lumpur",
        "city": "Kuala Lumpur",
        "country": "Malaysia",
        "stars": 5,
    },
    {
        "property_id": 1015,
        "name": "Renaissance Seoul",
        "city": "Seoul",
        "country": "South Korea",
        "stars": 5,
    },
    {
        "property_id": 1016,
        "name": "Hilton Doha",
        "city": "Doha",
        "country": "Qatar",
        "stars": 5,
    },
    {
        "property_id": 1017,
        "name": "Marriott Cairo",
        "city": "Cairo",
        "country": "Egypt",
        "stars": 5,
    },
    {
        "property_id": 1018,
        "name": "Hyatt Regency Mumbai",
        "city": "Mumbai",
        "country": "India",
        "stars": 5,
    },
    {
        "property_id": 1019,
        "name": "Sheraton Istanbul",
        "city": "Istanbul",
        "country": "Turkey",
        "stars": 5,
    },
    {
        "property_id": 1020,
        "name": "Novotel Bali Resort",
        "city": "Bali",
        "country": "Indonesia",
        "stars": 4,
    },
    {
        "property_id": 1021,
        "name": "Westin Osaka",
        "city": "Osaka",
        "country": "Japan",
        "stars": 5,
    },
    {
        "property_id": 1022,
        "name": "Holiday Inn Dublin",
        "city": "Dublin",
        "country": "Ireland",
        "stars": 4,
    },
    {
        "property_id": 1023,
        "name": "Accor Lisbon Centre",
        "city": "Lisbon",
        "country": "Portugal",
        "stars": 4,
    },
    {
        "property_id": 1024,
        "name": "Radisson Stockholm",
        "city": "Stockholm",
        "country": "Sweden",
        "stars": 4,
    },
    {
        "property_id": 1025,
        "name": "Fairmont Zurich",
        "city": "Zurich",
        "country": "Switzerland",
        "stars": 5,
    },
    {
        "property_id": 1026,
        "name": "Pullman Brussels",
        "city": "Brussels",
        "country": "Belgium",
        "stars": 4,
    },
    {
        "property_id": 1027,
        "name": "Mercure Vienna",
        "city": "Vienna",
        "country": "Austria",
        "stars": 4,
    },
    {
        "property_id": 1028,
        "name": "Hilton Prague",
        "city": "Prague",
        "country": "Czech Republic",
        "stars": 5,
    },
    {
        "property_id": 1029,
        "name": "Marriott Athens",
        "city": "Athens",
        "country": "Greece",
        "stars": 5,
    },
    {
        "property_id": 1030,
        "name": "Hyatt Auckland",
        "city": "Auckland",
        "country": "New Zealand",
        "stars": 5,
    },
    {
        "property_id": 1031,
        "name": "Sheraton Cape Town",
        "city": "Cape Town",
        "country": "South Africa",
        "stars": 5,
    },
    {
        "property_id": 1032,
        "name": "Novotel Nairobi",
        "city": "Nairobi",
        "country": "Kenya",
        "stars": 4,
    },
    {
        "property_id": 1033,
        "name": "Westin Mexico City",
        "city": "Mexico City",
        "country": "Mexico",
        "stars": 5,
    },
    {
        "property_id": 1034,
        "name": "Holiday Inn São Paulo",
        "city": "São Paulo",
        "country": "Brazil",
        "stars": 4,
    },
    {
        "property_id": 1035,
        "name": "Hilton Buenos Aires",
        "city": "Buenos Aires",
        "country": "Argentina",
        "stars": 5,
    },
    {
        "property_id": 1036,
        "name": "Marriott Lima",
        "city": "Lima",
        "country": "Peru",
        "stars": 5,
    },
    {
        "property_id": 1037,
        "name": "Hyatt Santiago",
        "city": "Santiago",
        "country": "Chile",
        "stars": 5,
    },
    {
        "property_id": 1038,
        "name": "Sheraton Bogotá",
        "city": "Bogotá",
        "country": "Colombia",
        "stars": 5,
    },
    {
        "property_id": 1039,
        "name": "Radisson Copenhagen",
        "city": "Copenhagen",
        "country": "Denmark",
        "stars": 4,
    },
    {
        "property_id": 1040,
        "name": "Fairmont Helsinki",
        "city": "Helsinki",
        "country": "Finland",
        "stars": 5,
    },
    {
        "property_id": 1041,
        "name": "Mercure Warsaw",
        "city": "Warsaw",
        "country": "Poland",
        "stars": 4,
    },
    {
        "property_id": 1042,
        "name": "Hilton Budapest",
        "city": "Budapest",
        "country": "Hungary",
        "stars": 5,
    },
    {
        "property_id": 1043,
        "name": "Marriott Reykjavik",
        "city": "Reykjavik",
        "country": "Iceland",
        "stars": 5,
    },
    {
        "property_id": 1044,
        "name": "Hyatt Muscat",
        "city": "Muscat",
        "country": "Oman",
        "stars": 5,
    },
    {
        "property_id": 1045,
        "name": "Sheraton Riyadh",
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "stars": 5,
    },
    {
        "property_id": 1046,
        "name": "Novotel Colombo",
        "city": "Colombo",
        "country": "Sri Lanka",
        "stars": 4,
    },
    {
        "property_id": 1047,
        "name": "Westin Kathmandu",
        "city": "Kathmandu",
        "country": "Nepal",
        "stars": 5,
    },
    {
        "property_id": 1048,
        "name": "Holiday Inn Dhaka",
        "city": "Dhaka",
        "country": "Bangladesh",
        "stars": 4,
    },
    {
        "property_id": 1049,
        "name": "Hilton Hanoi",
        "city": "Hanoi",
        "country": "Vietnam",
        "stars": 5,
    },
    {
        "property_id": 1050,
        "name": "Marriott Hong Kong",
        "city": "Hong Kong",
        "country": "Hong Kong",
        "stars": 5,
    },
]

CAMPAIGNS = ["Summer Sale", "Black Friday", "Holiday Deals", "Flash Sale"]

TRAFFIC_SOURCES = ["Google Ads", "Facebook Ads", "Instagram", "Organic", "Email"]

DEVICES = ["Desktop", "Mobile", "Tablet"]

LOYALTY = ["None", "Genius Level 1", "Genius Level 2", "Genius Level 3"]
